version: '2'

volumes: 
  jenkins_home:
    external: true

services:
  master:
    build: 
      context: ./master
      dockerfile: Dockerfile
    environment: 
      JENKINS_USER: admin
      JENKINS_PASS: admin
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes: 
      - jenkins_home:/var/jenkins_home
  slave:
    build: 
      context: ./slave
      dockerfile: Dockerfile
    restart: always
    environment:
      JENKINS_URL: http://master:8080
      JENKINS_USER: admin
      JENKINS_PASS: admin
      SLAVE_LABELS: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - master