version: '2'

volumes: 
  jenkins_home:
    external: true
services: 
  jenkins:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8090:8080
    volumes: 
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock